# conda env create -f environment.yml
name: pride-bluesky-bot
channels:
  - openms
  - conda-forge
  - bioconda
dependencies:
  - python=3.8.18
  - fastapi
  - uvicorn
  - transformers
  - pip
  - pip:
    - torch==2.2.2
    - APScheduler
    - aiolimiter